const float SCREEN_WIDTH = 1980.0f;
const float SCREEN_HEIGHT = 1080.0f;
const float PLAYING_FIELD_WIDTH = 800.0f;
const float PLAYING_FIELD_HEIGHT = 600.0f;

// const float PLAYING_FIELD_WIDTH = SCREEN_WIDTH - 10.0f;
// const float PLAYING_FIELD_HEIGHT = SCREEN_HEIGHT - 10.0f;